# Exploring Data with Pandas

This notebook serves as a practical introduction to the Pandas library in Python. It walks through key functionalities such as reading data, filtering, grouping, and basic data manipulation techniques.

In [2]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv("Diwali Sales Data.csv",encoding ="unicode_escape")

In [20]:
df.info

<bound method DataFrame.info of        User_ID    Cust_name Product_ID Gender Age Group  Age  Marital_Status  \
0      1002903    Sanskriti  P00125942      F     26-35   28               0   
1      1000732       Kartik  P00110942      F     26-35   35               1   
2      1001990        Bindu  P00118542      F     26-35   35               1   
3      1001425       Sudevi  P00237842      M      0-17   16               0   
4      1000588         Joni  P00057942      M     26-35   28               1   
...        ...          ...        ...    ...       ...  ...             ...   
11246  1000695      Manning  P00296942      M     18-25   19               1   
11247  1004089  Reichenbach  P00171342      M     26-35   33               0   
11248  1001209        Oshin  P00201342      F     36-45   40               0   
11249  1004023       Noonan  P00059442      M     36-45   37               0   
11250  1002744      Brumley  P00281742      F     18-25   19               0   

       

In [21]:
df.shape

(11251, 15)

In [22]:
df.show

AttributeError: 'DataFrame' object has no attribute 'show'

In [26]:
df.head(1)

User_ID  Cust_name Product_ID Gender Age Group  Age  Marital_Status  \
0  1002903  Sanskriti  P00125942      F     26-35   28               0   

         State     Zone  Occupation Product_Category  Orders   Amount  Status  \
0  Maharashtra  Western  Healthcare             Auto       1  23952.0     NaN   

   unnamed1  
0       NaN

In [30]:
#sort values

df.sort_values(by = 'Cust_name',inplace = True)

In [31]:
df.head(10)

User_ID Cust_name Product_ID Gender Age Group  Age  Marital_Status  \
10329  1001407     Aaron  P00184942      M     36-45   38               0   
1497   1001407     Aaron  P00219942      M     36-45   41               1   
8508   1001407     Aaron  P00125742      M     36-45   37               1   
10500  1005406     Aaron  P00174042      M     36-45   39               1   
7561   1000420     Aaron  P00136842      F     36-45   45               0   
3334   1001359   Aarushi  P00191642      F     36-45   42               1   
7984   1000646   Aarushi  P00002042      F     36-45   38               1   
5772   1000646   Aarushi  P00112142      M     36-45   44               0   
2375   1002483   Aarushi  P00313442      F       55+   66               0   
1952   1000646   Aarushi  P00042142      F     36-45   44               0   

               State      Zone   Occupation       Product_Category  Orders  \
10329      Karnataka  Southern         Govt        Household items       1   
1497     Uttarakhand   Central  Hospitality           Games & Toys       4   
8508   Uttar Pradesh   Central    IT Sector     Clothing & Apparel       3   
10500          Delhi   Central     Aviation        Household items       1   
7561     Maharashtra   Western      Banking     Clothing & Apparel       4   
3334       Karnataka  Southern   Automobile                   Food       1   
7984       Rajasthan  Northern      Banking  Electronics & Gadgets       3   
5772           Bihar   Eastern      Banking  Electronics & Gadgets       1   
2375   Uttar Pradesh   Central       Retail                   Food       1   
1952       Karnataka  Southern   Healthcare                   Food       4   

        Amount  Status  unnamed1  
10329   3037.0     NaN       NaN  
1497   16239.0     NaN       NaN  
8508    5414.0     NaN       NaN  
10500   2383.0     NaN       NaN  
7561    6900.0     NaN       NaN  
3334   11878.0     NaN       NaN  
7984    6044.0     NaN       NaN  
5772    8063.0     NaN       NaN  
2375   15218.0     NaN       NaN  
1952   15600.0     NaN       NaN

In [32]:
df.info

<bound method DataFrame.info of        User_ID Cust_name Product_ID Gender Age Group  Age  Marital_Status  \
10329  1001407     Aaron  P00184942      M     36-45   38               0   
1497   1001407     Aaron  P00219942      M     36-45   41               1   
8508   1001407     Aaron  P00125742      M     36-45   37               1   
10500  1005406     Aaron  P00174042      M     36-45   39               1   
7561   1000420     Aaron  P00136842      F     36-45   45               0   
...        ...       ...        ...    ...       ...  ...             ...   
9954   1004821    percer  P00047042      M     18-25   21               0   
9408   1004090    percer  P00233442      M       55+   63               1   
368    1002664    percer  P00090942      M     36-45   45               0   
7658   1004090    percer  P00344142      F       55+   88               0   
1874   1002664    percer  P00221142      F     36-45   38               0   

                  State      Zone    Occupa

In [33]:
df[Amount].fillna(0)

NameError: name 'Amount' is not defined

# aggregate Function

In [12]:
a = np.array([1,99,2,3,10,5,6,7,8,9,33,56,77,8,543,46,5464])

In [13]:
print(np.sort(a))

[   1    2    3    5    6    7    8    8    9   10   33   46   56   77
   99  543 5464]


In [17]:
a[1:5]

array([99,  2,  3, 10])

In [20]:
a[::-1]

array([5464,   46,  543,    8,   77,   56,   33,    9,    8,    7,    6,
          5,   10,    3,    2,   99,    1])

In [23]:
b=np.array([100,200,300,400])

In [24]:
np.concatenate((a,b),axis = 0)

array([   1,   99,    2,    3,   10,    5,    6,    7,    8,    9,   33,
         56,   77,    8,  543,   46, 5464,  100,  200,  300,  400])

In [26]:
np.hsplit(a,2)

ValueError: array split does not result in an equal division

### Conclusion

Through this hands-on notebook, we explored core features of the Pandas library. These operations form the foundation for more advanced data analysis and machine learning workflows in Python.